"use client";

import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";

type Prize = { id: string; name: string; weight: number; active: boolean; metadata: Record<string, unknown> | null };
type Settings = {
  wheel_style: string; wheel_theme: string; segment_sizing: "equal" | "weight"; min_visual_segments: number;
  wheel_border_color: string; wheel_border_thickness: number; center_color: string; center_size: number;
  pointer_color: string; prize_text_color: string; prize_text_size: number; text_orientation: string; animation_duration: number;
};
type WheelStyleName = "classic" | "modern" | "bold" | "elegant" | "custom";

const defaults: Settings = { wheel_style:"classic", wheel_theme:"multicolor", segment_sizing:"equal", min_visual_segments:8, wheel_border_color:"#111827", wheel_border_thickness:8, center_color:"#e31b23", center_size:50, pointer_color:"#e31b23", prize_text_color:"#ffffff", prize_text_size:13, text_orientation:"auto", animation_duration:5.2 };
const palettes: Record<string,string[]> = { "red-white":["#dc2626","#ffffff"], gold:["#d4a017","#fff7d6","#7c5b00"], blue:["#2563eb","#60a5fa","#1e3a8a"], green:["#16a34a","#86efac","#14532d"], multicolor:["#e31b23","#111827","#f59e0b","#2563eb","#16a34a","#7c3aed","#db2777","#0891b2"], custom:["#e31b23","#111827","#f59e0b","#2563eb"] };
const styleCards:{value:WheelStyleName;label:string;description:string;colors:string[];border:string;center:string;pointer:string;borderWidth:number}[]=[
  {value:"classic",label:"Classic",description:"Traditional clean look",colors:["#e31b23","#f59e0b","#2563eb","#16a34a"],border:"#e31b23",center:"#e31b23",pointer:"#e31b23",borderWidth:5},
  {value:"modern",label:"Modern",description:"Clean and minimal",colors:["#fb7185","#60a5fa","#a78bfa","#6ee7b7","#fdba74"],border:"#ffffff",center:"#ffffff",pointer:"#fb7185",borderWidth:3},
  {value:"bold",label:"Bold",description:"Strong and eye-catching",colors:["#ef4444","#f59e0b","#16a34a","#2563eb","#7c3aed"],border:"#111827",center:"#111827",pointer:"#dc2626",borderWidth:9},
  {value:"elegant",label:"Elegant",description:"Refined premium look",colors:["#0f766e","#f5e6c8","#d4a017","#67a99a","#c97d60"],border:"#b68a2c",center:"#b68a2c",pointer:"#b91c1c",borderWidth:4},
  {value:"custom",label:"Custom",description:"Use your own settings",colors:["#d1d5db","#f3f4f6","#9ca3af","#e5e7eb"],border:"#6b7280",center:"#6b7280",pointer:"#4b5563",borderWidth:4},
];
const isHex=(v:unknown):v is string=>typeof v==="string"&&/^#[0-9a-fA-F]{6}$/.test(v);
const numberValue=(v:unknown,f:number,min:number,max:number)=>typeof v==="number"?Math.min(max,Math.max(min,v)):f;
function parseSettings(a:Record<string,unknown>):Settings{return{wheel_style:typeof a.wheel_style==="string"?a.wheel_style:defaults.wheel_style,wheel_theme:typeof a.wheel_theme==="string"?a.wheel_theme:defaults.wheel_theme,segment_sizing:a.segment_sizing==="weight"?"weight":"equal",min_visual_segments:numberValue(a.min_visual_segments,defaults.min_visual_segments,0,24),wheel_border_color:isHex(a.wheel_border_color)?a.wheel_border_color:defaults.wheel_border_color,wheel_border_thickness:numberValue(a.wheel_border_thickness,defaults.wheel_border_thickness,0,24),center_color:isHex(a.center_color)?a.center_color:defaults.center_color,center_size:numberValue(a.center_size,defaults.center_size,24,120),pointer_color:isHex(a.pointer_color)?a.pointer_color:defaults.pointer_color,prize_text_color:isHex(a.prize_text_color)?a.prize_text_color:defaults.prize_text_color,prize_text_size:numberValue(a.prize_text_size,defaults.prize_text_size,9,24),text_orientation:typeof a.text_orientation==="string"?a.text_orientation:defaults.text_orientation,animation_duration:numberValue(a.animation_duration,defaults.animation_duration,2,10)}}

function MiniStyleWheel({style,selected,onClick}:{style:(typeof styleCards)[number];selected:boolean;onClick:()=>void}){
  const bg=`conic-gradient(${style.colors.map((c,i)=>`${c} ${i*360/style.colors.length}deg ${(i+1)*360/style.colors.length}deg`).join(",")})`;
  return <button type="button" onClick={onClick} aria-pressed={selected} style={{background:"#fff",border:selected?"2px solid #2563eb":"1px solid #d1d5db",borderRadius:10,padding:"12px 8px",cursor:"pointer",boxShadow:selected?"0 0 0 2px rgba(37,99,235,.12)":"none",minWidth:0}}>
    <div style={{position:"relative",width:82,height:82,margin:"0 auto 8px"}}>
      <div style={{position:"absolute",top:-5,left:"50%",transform:"translateX(-50%)",zIndex:3,width:0,height:0,borderLeft:"7px solid transparent",borderRight:"7px solid transparent",borderTop:`15px solid ${style.pointer}`}}/>
      <div style={{width:"100%",height:"100%",boxSizing:"border-box",borderRadius:"50%",padding:style.borderWidth,background:style.border}}><div style={{position:"relative",width:"100%",height:"100%",borderRadius:"50%",background:bg}}><div style={{position:"absolute",top:"50%",left:"50%",width:18,height:18,transform:"translate(-50%,-50%)",borderRadius:"50%",background:style.center,border:"2px solid #fff"}}/></div></div>
    </div>
    <div style={{fontWeight:800,fontSize:14,color:"#111827"}}>{style.label}</div>
    <div style={{fontSize:11,color:"#6b7280",marginTop:3,lineHeight:1.25}}>{style.description}</div>
    <div style={{margin:"8px auto 0",width:16,height:16,borderRadius:"50%",border:selected?"5px solid #2563eb":"1px solid #9ca3af",boxSizing:"border-box"}}/>
  </button>;
}

export default function WheelCustomization({campaignGameId}:{campaignGameId:string}){
  const [target,setTarget]=useState<HTMLElement|null>(null);
  const [base,setBase]=useState<Record<string,unknown>>({}); const [settings,setSettings]=useState<Settings>(defaults); const [prizes,setPrizes]=useState<Prize[]>([]); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");

  useEffect(()=>{let attempts=0;const find=()=>{const heading=Array.from(document.querySelectorAll("h2")).find(node=>node.textContent?.trim()==="Customer View");const panel=heading?.closest(".admin-panel");if(panel instanceof HTMLElement){setTarget(panel);return true}return false};if(find())return;const timer=window.setInterval(()=>{attempts+=1;if(find()||attempts>=40)window.clearInterval(timer)},100);return()=>window.clearInterval(timer)},[]);
  useEffect(()=>{Promise.all([fetch(`/api/admin/campaign-games/${campaignGameId}`,{cache:"no-store"}).then(r=>r.json()),fetch(`/api/admin/campaign-games/${campaignGameId}/prizes`,{cache:"no-store"}).then(r=>r.json())]).then(([c,p])=>{const a=(c.campaignGame?.appearance||{}) as Record<string,unknown>;setBase(a);setSettings(parseSettings(a));setPrizes(Array.isArray(p.prizes)?p.prizes:[])}).catch(()=>setMessage("Unable to load wheel customization."))},[campaignGameId]);

  const segments=useMemo(()=>{const active=prizes.filter(p=>p.active);if(!active.length)return[];const targetCount=Math.max(active.length,settings.min_visual_segments||active.length);const copies=Math.max(1,Math.ceil(targetCount/active.length));const entries=Array.from({length:active.length*copies},(_,i)=>({prize:active[i%active.length],prizeIndex:i%active.length,copy:Math.floor(i/active.length)}));const counts=new Map<string,number>();entries.forEach(({prize})=>counts.set(prize.id,(counts.get(prize.id)||0)+1));const units=entries.map(({prize})=>settings.segment_sizing==="weight"?Math.max(0,prize.weight)/(counts.get(prize.id)||1):1);const total=units.reduce((a,b)=>a+b,0)||entries.length;let current=0;return entries.map((entry,i)=>{const size=(units[i]||1)*360/total,start=current,end=i===entries.length-1?360:current+size;current=end;const own=entry.prize.metadata?.segment_color,palette=palettes[settings.wheel_theme]||palettes.multicolor;return{...entry,start,end,center:start+(end-start)/2,color:isHex(own)?own:palette[entry.prizeIndex%palette.length]}})},[prizes,settings]);
  const wheelBackground=segments.length?`conic-gradient(${segments.map(s=>`${s.color} ${s.start}deg ${s.end}deg`).join(",")})`:"#e5e7eb";
  function update<K extends keyof Settings>(key:K,value:Settings[K]){setSettings(c=>({...c,[key]:value}));setMessage("")}
  function selectStyle(value:WheelStyleName){const preset=styleCards.find(s=>s.value===value);if(!preset)return;setSettings(c=>value==="custom"?{...c,wheel_style:value}:{...c,wheel_style:value,wheel_border_color:preset.border,wheel_border_thickness:preset.borderWidth,center_color:preset.center,pointer_color:preset.pointer});setMessage("")}
  async function save(){setSaving(true);setMessage("");try{const response=await fetch(`/api/admin/campaign-games/${campaignGameId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({appearance:{...base,...settings}})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Save failed.");const a=(result.campaignGame?.appearance||{...base,...settings}) as Record<string,unknown>;setBase(a);setSettings(parseSettings(a));setMessage("Wheel customization saved.")}catch(error){setMessage(error instanceof Error?error.message:"Save failed.")}finally{setSaving(false)}}
  const inputStyle={width:"100%",padding:"10px",border:"1px solid #d1d5db",borderRadius:"8px",boxSizing:"border-box" as const,background:"#ffffff"};
  const colorField=(label:string,key:"wheel_border_color"|"center_color"|"pointer_color"|"prize_text_color")=><div><b>{label}</b><div style={{display:"flex",gap:8,marginTop:6}}><input type="color" value={settings[key]} onChange={e=>update(key,e.target.value)} style={{width:48,height:40}}/><input value={settings[key]} readOnly style={inputStyle}/></div></div>;
  if(!target)return null;

  return createPortal(<div data-wheel-customization style={{marginTop:24,paddingTop:24,borderTop:"1px solid #e5e7eb"}}>
    <h3 style={{margin:"0 0 6px",fontSize:22}}>Wheel Customization</h3>
    <p style={{margin:"0 0 20px",color:"#6b7280"}}>Customize the campaign wheel. Visual segment sizing does not change backend winning probability.</p>

    <div style={{marginBottom:22}}><b style={{display:"block",marginBottom:10}}>Wheel Style</b><div style={{display:"grid",gridTemplateColumns:"repeat(5,minmax(105px,1fr))",gap:10,overflowX:"auto",paddingBottom:4}}>{styleCards.map(style=><MiniStyleWheel key={style.value} style={style} selected={settings.wheel_style===style.value} onClick={()=>selectStyle(style.value)}/>)}</div></div>

    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:16}}>
      <div><b>Quick Theme</b><select value={settings.wheel_theme} onChange={e=>update("wheel_theme",e.target.value)} style={{...inputStyle,marginTop:6}}><option value="red-white">Red &amp; White</option><option value="gold">Gold</option><option value="blue">Blue</option><option value="green">Green</option><option value="multicolor">Multicolor</option><option value="custom">Custom</option></select></div>
      <div><b>Segment Sizing</b><select value={settings.segment_sizing} onChange={e=>update("segment_sizing",e.target.value as Settings["segment_sizing"])} style={{...inputStyle,marginTop:6}}><option value="equal">Equal Size</option><option value="weight">Based on Prize Weight</option></select></div>
      <div><b>Minimum Visual Segments</b><select value={settings.min_visual_segments} onChange={e=>update("min_visual_segments",Number(e.target.value))} style={{...inputStyle,marginTop:6}}><option value={0}>Auto</option><option value={4}>4</option><option value={6}>6</option><option value={8}>8</option><option value={10}>10</option><option value={12}>12</option></select><small style={{color:"#6b7280"}}>4 prizes + 8 segments = each prize appears twice visually.</small></div>
      {colorField("Wheel Border Color","wheel_border_color")}{colorField("Center Circle Color","center_color")}{colorField("Pointer Color","pointer_color")}{colorField("Prize Text Color","prize_text_color")}
      <div><b>Border Thickness ({settings.wheel_border_thickness}px)</b><input type="range" min={0} max={24} value={settings.wheel_border_thickness} onChange={e=>update("wheel_border_thickness",Number(e.target.value))} style={{width:"100%"}}/></div>
      <div><b>Center Size ({settings.center_size}px)</b><input type="range" min={24} max={120} value={settings.center_size} onChange={e=>update("center_size",Number(e.target.value))} style={{width:"100%"}}/></div>
      <div><b>Prize Text Size ({settings.prize_text_size}px)</b><input type="range" min={9} max={24} value={settings.prize_text_size} onChange={e=>update("prize_text_size",Number(e.target.value))} style={{width:"100%"}}/></div>
      <div><b>Text Orientation</b><select value={settings.text_orientation} onChange={e=>update("text_orientation",e.target.value)} style={{...inputStyle,marginTop:6}}><option value="auto">Auto</option><option value="radial">Radial</option><option value="tangential">Tangential</option><option value="horizontal">Horizontal</option></select></div>
      <div><b>Spin Duration ({settings.animation_duration.toFixed(1)}s)</b><input type="range" min={2} max={10} step={0.2} value={settings.animation_duration} onChange={e=>update("animation_duration",Number(e.target.value))} style={{width:"100%"}}/></div>
    </div>
    <div style={{marginTop:24,padding:20,border:"1px solid #e5e7eb",borderRadius:12,background:"#f9fafb",textAlign:"center"}}><b>Live Wheel Preview — {styleCards.find(s=>s.value===settings.wheel_style)?.label||"Classic"}</b><div style={{position:"relative",width:300,height:300,maxWidth:"75vw",maxHeight:"75vw",margin:"16px auto 0"}}><div style={{position:"absolute",top:-3,left:"50%",transform:"translateX(-50%)",zIndex:9,width:0,height:0,borderLeft:"14px solid transparent",borderRight:"14px solid transparent",borderTop:`27px solid ${settings.pointer_color}`}}/><div style={{width:"100%",height:"100%",boxSizing:"border-box",borderRadius:"50%",padding:settings.wheel_border_thickness,background:settings.wheel_border_color}}><div style={{width:"100%",height:"100%",borderRadius:"50%",background:wheelBackground,position:"relative",overflow:"hidden",border:settings.wheel_style==="modern"?"1px solid #fff":"3px solid #fff",boxSizing:"border-box",boxShadow:settings.wheel_style==="elegant"?"inset 0 0 0 2px rgba(255,255,255,.6)":"none"}}>{segments.map(segment=>{const radial=segment.center-90,flip=radial>90||radial<-90,outer=settings.text_orientation==="tangential"?`translateY(-50%) rotate(${segment.center}deg)`:`translateY(-50%) rotate(${radial}deg)`,inner=settings.text_orientation==="horizontal"?`rotate(${-radial}deg)`:flip&&settings.text_orientation!=="tangential"?"rotate(180deg)":"none";return <div key={`${segment.prize.id}-${segment.copy}`} style={{position:"absolute",top:"50%",left:"50%",width:"32%",height:30,transform:outer,transformOrigin:"0 50%",display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{width:"100%",color:settings.prize_text_color,fontSize:settings.prize_text_size,fontWeight:settings.wheel_style==="bold"?900:800,textAlign:"center",lineHeight:1,overflowWrap:"anywhere",textShadow:"0 1px 3px #000",transform:inner}}>{segment.prize.name}</span></div>})}<div style={{position:"absolute",top:"50%",left:"50%",width:settings.center_size,height:settings.center_size,transform:"translate(-50%,-50%)",borderRadius:"50%",background:settings.center_color,border:settings.wheel_style==="modern"?"2px solid #fff":"4px solid #fff",zIndex:5}}/></div></div></div></div>
    <div style={{display:"flex",justifyContent:"flex-end",alignItems:"center",gap:12,marginTop:16}}>{message&&<span style={{fontSize:13,color:message.includes("saved")?"#065f46":"#b91c1c"}}>{message}</span>}<button type="button" className="primary-btn" onClick={save} disabled={saving}>{saving?"Saving...":"Save Wheel Customization"}</button></div>
  </div>,target);
}
