"use client";
import { useEffect, useState } from "react";

type RequestItem = { id: string; amount_lkr: number; payment_reference: string; status: string; review_notes: string | null; created_at: string; receipt_url: string | null; workspace_name: string; plan_name: string; plan_slug: string };
const panel: React.CSSProperties = { background: "white", border: "1px solid #e5e7eb", borderRadius: 12, padding: 18 };
export default function SubscriptionReviewManager({ canReview }: { canReview: boolean }) {
  const [requests, setRequests] = useState<RequestItem[]>([]), [busyId, setBusyId] = useState(""), [note, setNote] = useState<Record<string, string>>({}), [message, setMessage] = useState("");
  async function load() { const r = await fetch("/api/saas-admin/subscriptions", { cache: "no-store" }); const j = await r.json(); if (!r.ok) throw new Error(j.error || "Unable to load requests."); setRequests(j.requests ?? []); }
  useEffect(() => { load().catch(e => setMessage(e.message)); }, []);
  async function review(id: string, decision: "approve" | "reject") { setBusyId(id); setMessage(""); try { const r = await fetch("/api/saas-admin/subscriptions", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, decision, notes: note[id] || "" }) }); const j = await r.json(); if (!r.ok) throw new Error(j.error || "Unable to review request."); setMessage(decision === "approve" ? "Subscription approved." : "Request rejected."); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to review request."); } finally { setBusyId(""); } }
  const pending = requests.filter(r => r.status === "pending"), history = requests.filter(r => r.status !== "pending");
  return <div><h1 style={{ marginBottom: 6 }}>Subscription Requests</h1><p style={{ color: "#666", marginTop: 0 }}>Review payment references and privately uploaded receipts.</p>{message && <p role="status">{message}</p>}
    <h2>Awaiting review ({pending.length})</h2>{pending.length ? <div style={{ display: "grid", gap: 14 }}>{pending.map(r => <section key={r.id} style={panel}><h3 style={{ marginTop: 0 }}>{r.workspace_name} · {r.plan_name}</h3><p><strong>LKR {Number(r.amount_lkr).toLocaleString("en-LK", { minimumFractionDigits: 2 })}</strong> · Reference: {r.payment_reference}</p><p>Submitted {new Date(r.created_at).toLocaleString()}</p>{r.receipt_url ? <a href={r.receipt_url} target="_blank" rel="noreferrer">View payment receipt</a> : <p>Receipt link unavailable. Refresh the page to request a new secure link.</p>}{canReview && <><label style={{ display: "block", margin: "14px 0" }}>Review note (optional)<textarea value={note[r.id] ?? ""} maxLength={1000} onChange={e => setNote(v => ({ ...v, [r.id]: e.target.value }))} style={{ display: "block", width: "100%", minHeight: 70, marginTop: 5 }} /></label><div style={{ display: "flex", gap: 10 }}><button className="primary-btn" disabled={busyId === r.id} onClick={() => review(r.id, "approve")}>{busyId === r.id ? "Saving…" : "Approve"}</button><button className="secondary-btn" disabled={busyId === r.id} onClick={() => review(r.id, "reject")}>Reject</button></div></>}</section>)}</div> : <p>No requests are awaiting review.</p>}
    <h2 style={{ marginTop: 28 }}>Reviewed requests</h2>{history.length ? <div style={{ display: "grid", gap: 8 }}>{history.map(r => <div key={r.id} style={panel}><strong>{r.workspace_name} · {r.plan_name}</strong> · {r.status} · LKR {Number(r.amount_lkr).toLocaleString("en-LK")}<div style={{ color: "#666", fontSize: 13 }}>Ref: {r.payment_reference} · {new Date(r.created_at).toLocaleDateString()}{r.review_notes ? ` · ${r.review_notes}` : ""}</div>{r.receipt_url && <a href={r.receipt_url} target="_blank" rel="noreferrer">View receipt</a>}</div>)}</div> : <p>No reviewed requests.</p>}</div>;
}
