"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../../lib/supabase";

type ReportRow = {
  session_id: string; played_at: string; mobile: string;
  customer_name: string | null; customer_email: string | null; customer_address: string | null;
  campaign_name: string; game_name: string; public_slug: string;
  result_type: string; prize_name: string | null; coupon_code: string | null; coupon_status: string | null;
};

type ReportField = "date" | "mobile" | "name" | "email" | "address" | "campaign" | "game" | "result" | "prize" | "coupon" | "couponStatus";
type ExportField = ReportField;

const fieldOptions: { key: ReportField; label: string }[] = [
  { key: "date", label: "Date & Time" }, { key: "mobile", label: "Mobile Number" },
  { key: "name", label: "Name" }, { key: "email", label: "Email Address" }, { key: "address", label: "Address" },
  { key: "campaign", label: "Campaign" }, { key: "game", label: "Game" }, { key: "result", label: "Result" },
  { key: "prize", label: "Prize" }, { key: "coupon", label: "Coupon Code" }, { key: "couponStatus", label: "Coupon Status" },
];
const exportFieldOptions = fieldOptions;
const defaultTableFields: ReportField[] = ["date", "mobile", "name", "campaign", "game", "result", "prize", "coupon"];

export default function WinnersPage() {
  const [rows, setRows] = useState<ReportRow[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [campaignFilter, setCampaignFilter] = useState("all"); const [gameFilter, setGameFilter] = useState("all"); const [resultFilter, setResultFilter] = useState("all");
  const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState("");
  const [showExportOptions, setShowExportOptions] = useState(false); const [showTableOptions, setShowTableOptions] = useState(false);
  const [exportFields, setExportFields] = useState<ExportField[]>(exportFieldOptions.map((field) => field.key));
  const [tableFields, setTableFields] = useState<ReportField[]>(defaultTableFields);

  useEffect(() => { async function loadReporting() { const { data, error } = await supabase.rpc("get_game_reporting"); if (error) setError(error.message); else setRows(data ?? []); setLoading(false); } loadReporting(); }, []);
  const campaigns = useMemo(() => Array.from(new Set(rows.map((r) => r.campaign_name))).sort(), [rows]);
  const games = useMemo(() => Array.from(new Set(rows.map((r) => r.game_name))).sort(), [rows]);
  const filteredRows = useMemo(() => rows.filter((row) => { const played = new Date(row.played_at); const fromOk = !dateFrom || played >= new Date(`${dateFrom}T00:00:00`); const toOk = !dateTo || played <= new Date(`${dateTo}T23:59:59.999`); return (campaignFilter === "all" || row.campaign_name === campaignFilter) && (gameFilter === "all" || row.game_name === gameFilter) && (resultFilter === "all" || row.result_type === resultFilter) && fromOk && toOk; }), [rows, campaignFilter, gameFilter, resultFilter, dateFrom, dateTo]);
  const summary = useMemo(() => { const completed = filteredRows.filter((r) => ["win", "no_prize", "completed"].includes(r.result_type)); const wins = filteredRows.filter((r) => r.result_type === "win").length; const noPrize = filteredRows.filter((r) => r.result_type === "no_prize").length; const totalParticipants = new Set(filteredRows.map((r) => r.mobile).filter(Boolean)).size; return { totalParticipants, totalSpins: completed.length, wins, noPrize, winningRate: completed.length ? ((wins / completed.length) * 100).toFixed(1) : "0.0" }; }, [filteredRows]);
  function clearFilters() { setCampaignFilter("all"); setGameFilter("all"); setResultFilter("all"); setDateFrom(""); setDateTo(""); }
  function toggleExportField(field: ExportField) { setExportFields((current) => current.includes(field) ? current.filter((item) => item !== field) : [...current, field]); }
  function toggleTableField(field: ReportField) { setTableFields((current) => current.includes(field) ? current.filter((item) => item !== field) : [...current, field]); }
  function fieldValue(row: ReportRow, field: ReportField): string | null { if (field === "date") return new Date(row.played_at).toLocaleString(); if (field === "mobile") return row.mobile; if (field === "name") return row.customer_name; if (field === "email") return row.customer_email; if (field === "address") return row.customer_address; if (field === "campaign") return row.campaign_name; if (field === "game") return row.game_name; if (field === "result") return row.result_type === "win" ? "Winning" : row.result_type === "no_prize" ? "No Prize" : row.result_type; if (field === "prize") return row.prize_name; if (field === "coupon") return row.coupon_code; return row.coupon_status; }
  function exportCsv() { if (!exportFields.length || !filteredRows.length) return; const selected = exportFieldOptions.filter((field) => exportFields.includes(field.key)); const escapeCsv = (value: string | null) => `"${String(value ?? "").replace(/"/g, '""')}"`; const lines = filteredRows.map((row) => selected.map((field) => escapeCsv(fieldValue(row, field.key))).join(",")); const csv = "\uFEFF" + selected.map((field) => escapeCsv(field.label)).join(",") + "\n" + lines.join("\n"); const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `game-report-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 0); setShowExportOptions(false); }
  const cardStyle = { background: "#fff", border: "1px solid #e5e7eb", borderRadius: "16px", padding: "20px", boxShadow: "0 4px 14px rgba(0,0,0,.05)" }; const inputStyle = { minWidth: "165px", padding: "10px 12px", border: "1px solid #d1d5db", borderRadius: "10px", background: "#fff" }; const buttonStyle = { padding: "10px 16px", borderRadius: "10px", border: "1px solid #d1d5db", background: "#fff", cursor: "pointer", fontWeight: 700 };
  const selectedTableOptions = fieldOptions.filter((field) => tableFields.includes(field.key));
  return <div><div className="admin-header"><div><p className="eyebrow">REPORTING</p><h1>Game Reporting</h1><p>Monitor spins, winning performance and prize results across campaigns.</p></div></div>{error && <div className="error-box">{error}</div>}
  {!loading && <><div style={{display:"flex",flexWrap:"wrap",gap:"12px",marginBottom:"12px"}}><select value={campaignFilter} onChange={(e)=>setCampaignFilter(e.target.value)} style={inputStyle}><option value="all">All Campaigns</option>{campaigns.map((n)=><option key={n}>{n}</option>)}</select><select value={gameFilter} onChange={(e)=>setGameFilter(e.target.value)} style={inputStyle}><option value="all">All Games</option>{games.map((n)=><option key={n}>{n}</option>)}</select><select value={resultFilter} onChange={(e)=>setResultFilter(e.target.value)} style={inputStyle}><option value="all">All Results</option><option value="win">Winning</option><option value="no_prize">No Prize</option></select><input type="date" value={dateFrom} onChange={(e)=>setDateFrom(e.target.value)} style={inputStyle}/><input type="date" value={dateTo} onChange={(e)=>setDateTo(e.target.value)} style={inputStyle}/><button onClick={clearFilters} style={buttonStyle}>Clear Filters</button><button onClick={()=>setShowTableOptions(true)} style={buttonStyle}>Table Columns</button><button onClick={()=>setShowExportOptions(true)} disabled={!filteredRows.length} style={{...buttonStyle,background:"#111827",color:"#fff",opacity:filteredRows.length?1:.5}}>Export CSV</button></div><div style={{fontSize:"13px",color:"#6b7280",marginBottom:"18px"}}>Showing {filteredRows.length} record{filteredRows.length===1?"":"s"}. CSV export uses the currently selected filters.</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:"14px",marginBottom:"20px"}}>{[["TOTAL PARTICIPANTS",summary.totalParticipants],["TOTAL SPINS",summary.totalSpins],["WINS",summary.wins],["NO-PRIZE RESULTS",summary.noPrize],["WINNING RATE",`${summary.winningRate}%`]].map(([label,value])=><div key={label} style={cardStyle}><div style={{fontSize:"13px",color:"#6b7280",fontWeight:700}}>{label}</div><div style={{fontSize:"30px",fontWeight:900,marginTop:"6px"}}>{value}</div></div>)}</div></>}
  <div className="admin-panel"><div style={{marginBottom:"18px"}}><h2 style={{margin:0}}>Spin History</h2><p style={{margin:"6px 0 0",color:"#6b7280"}}>Detailed completed spin results, customer details, prizes and coupon activity.</p></div>{loading?<p>Loading reporting data...</p>:filteredRows.length===0?<p className="empty">No spin records match the selected filters.</p>:tableFields.length===0?<p className="empty">Select at least one table column to display spin history.</p>:<div className="overflow-x-auto"><table><thead><tr>{selectedTableOptions.map((field)=><th key={field.key}>{field.label}</th>)}</tr></thead><tbody>{filteredRows.map((row)=><tr key={row.session_id}>{selectedTableOptions.map((field)=><td key={field.key}>{field.key==="result"?<strong>{fieldValue(row,field.key)||"—"}</strong>:fieldValue(row,field.key)||"—"}</td>)}</tr>)}</tbody></table></div>}</div>
  {showTableOptions&&<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.45)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:10000,padding:"20px"}} onClick={()=>setShowTableOptions(false)}><div style={{background:"#fff",borderRadius:"18px",padding:"24px",width:"100%",maxWidth:"520px",boxShadow:"0 20px 60px rgba(0,0,0,.2)"}} onClick={(e)=>e.stopPropagation()}><h2 style={{margin:"0 0 6px"}}>Table Columns</h2><p style={{margin:"0 0 18px",color:"#6b7280"}}>Choose the details to display in Spin History.</p><div style={{display:"flex",gap:"10px",marginBottom:"16px"}}><button onClick={()=>setTableFields(fieldOptions.map((field)=>field.key))} style={buttonStyle}>Select All</button><button onClick={()=>setTableFields(defaultTableFields)} style={buttonStyle}>Reset Default</button><button onClick={()=>setTableFields([])} style={buttonStyle}>Clear All</button></div><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:"12px",marginBottom:"22px"}}>{fieldOptions.map((field)=><label key={field.key} style={{display:"flex",alignItems:"center",gap:"9px",padding:"10px",border:"1px solid #e5e7eb",borderRadius:"10px",cursor:"pointer"}}><input type="checkbox" checked={tableFields.includes(field.key)} onChange={()=>toggleTableField(field.key)}/><span>{field.label}</span></label>)}</div><div style={{display:"flex",justifyContent:"flex-end"}}><button onClick={()=>setShowTableOptions(false)} style={{...buttonStyle,background:"#111827",color:"#fff"}}>Done</button></div></div></div>}
  {showExportOptions&&<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.45)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:10000,padding:"20px"}} onClick={()=>setShowExportOptions(false)}><div style={{background:"#fff",borderRadius:"18px",padding:"24px",width:"100%",maxWidth:"520px",boxShadow:"0 20px 60px rgba(0,0,0,.2)"}} onClick={(e)=>e.stopPropagation()}><h2 style={{margin:"0 0 6px"}}>Export Options</h2><p style={{margin:"0 0 18px",color:"#6b7280"}}>Choose the fields to include in your CSV report.</p><div style={{display:"flex",gap:"10px",marginBottom:"16px"}}><button onClick={()=>setExportFields(exportFieldOptions.map((field)=>field.key))} style={buttonStyle}>Select All</button><button onClick={()=>setExportFields([])} style={buttonStyle}>Clear All</button></div><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:"12px",marginBottom:"22px"}}>{exportFieldOptions.map((field)=><label key={field.key} style={{display:"flex",alignItems:"center",gap:"9px",padding:"10px",border:"1px solid #e5e7eb",borderRadius:"10px",cursor:"pointer"}}><input type="checkbox" checked={exportFields.includes(field.key)} onChange={()=>toggleExportField(field.key)}/><span>{field.label}</span></label>)}</div><div style={{display:"flex",justifyContent:"flex-end",gap:"10px"}}><button onClick={()=>setShowExportOptions(false)} style={buttonStyle}>Cancel</button><button onClick={exportCsv} disabled={!exportFields.length} style={{...buttonStyle,background:"#111827",color:"#fff",opacity:exportFields.length?1:.5}}>Export {filteredRows.length} Records</button></div></div></div>}</div>;
}
