import { notFound } from "next/navigation";
import { createSupabaseServerClient } from "../../../lib/supabase-server";
import SpinAndWinGame from "../../../components/games/SpinAndWinGame";
import ScratchAndWinGame from "../../../components/games/ScratchAndWinGame";
import PickACardGame from "../../../components/games/PickACardGame";
type P={params:Promise<{slug:string}>};type R=Record<string,unknown>;type Mode="off"|"optional"|"required";type Details={name:Mode;email:Mode;address:Mode};
const text=(a:R,k:string,f:string)=>typeof a[k]==="string"?a[k] as string:f;const num=(a:R,k:string,f:number,min:number,max:number)=>typeof a[k]==="number"&&Number.isFinite(a[k])?Math.min(max,Math.max(min,a[k] as number)):f;const single=<T,>(v:T|T[]|null):T|null=>Array.isArray(v)?v[0]??null:v;const norm=(v:string)=>v.trim().toLowerCase().replace(/[\s_]+/g,"-");
function details(r:R|null):Details{const raw=r?.customer_details,d=typeof raw==="object"&&raw&&!Array.isArray(raw)?raw as R:{};const m=(v:unknown):Mode=>v==="optional"||v==="required"?v:"off";return{name:m(d.name),email:m(d.email),address:m(d.address)}}
function spin(a:R|null){const x=a??{};return{title:text(x,"title","SPIN & WIN"),subtitle:text(x,"subtitle","Spin daily and win exciting rewards!"),button_text:text(x,"button_text","SPIN NOW"),page_background_color:text(x,"page_background_color","#ffffff"),button_color:text(x,"button_color","#e31b23"),button_text_color:text(x,"button_text_color","#ffffff"),wheel_style:text(x,"wheel_style","classic"),wheel_theme:text(x,"wheel_theme","multicolor"),segment_sizing:x.segment_sizing==="weight"?"weight" as const:"equal" as const,min_visual_segments:Math.round(num(x,"min_visual_segments",8,1,24)),wheel_border_color:text(x,"wheel_border_color","#111827"),wheel_border_thickness:num(x,"wheel_border_thickness",8,0,20),center_color:text(x,"center_color","#e31b23"),center_size:num(x,"center_size",50,30,100),pointer_color:text(x,"pointer_color","#111827"),prize_text_color:text(x,"prize_text_color","#ffffff"),prize_text_size:num(x,"prize_text_size",13,8,24),text_orientation:(x.text_orientation==="radial"||x.text_orientation==="tangential"||x.text_orientation==="horizontal"?x.text_orientation:"auto") as "auto"|"radial"|"tangential"|"horizontal",animation_duration:num(x,"animation_duration",4.2,2,10)}}
function scratch(a:R|null){const x=a??{};return{title:text(x,"title","SCRATCH & WIN"),subtitle:text(x,"subtitle","Scratch the card to reveal your result!"),button_text:text(x,"button_text","START SCRATCHING"),page_background_color:text(x,"page_background_color","#f8fafc"),button_color:text(x,"button_color","#e31b23"),button_text_color:text(x,"button_text_color","#ffffff"),scratch_style:text(x,"scratch_style","classic"),scratch_cover_color:text(x,"scratch_cover_color","#6b7280"),scratch_cover_alt_color:text(x,"scratch_cover_alt_color","#9ca3af"),scratch_card_background:text(x,"scratch_card_background","#fff7ed"),scratch_card_border_color:text(x,"scratch_card_border_color","#111827"),scratch_card_border_thickness:num(x,"scratch_card_border_thickness",5,0,16),scratch_card_radius:num(x,"scratch_card_radius",22,0,40),scratch_instruction:text(x,"scratch_instruction","SCRATCH HERE"),scratch_reveal_percent:num(x,"scratch_reveal_percent",50,20,90)}}
function cards(a:R|null){const x=a??{};return{title:text(x,"title","PICK A CARD"),subtitle:text(x,"subtitle","Pick a card and reveal your reward!"),button_text:text(x,"button_text","ENTER YOUR MOBILE, THEN PICK A CARD"),page_background_color:text(x,"page_background_color","#f8fafc"),button_color:text(x,"button_color","#0f766e"),button_text_color:text(x,"button_text_color","#ffffff"),card_back_color:text(x,"card_back_color","#0f766e"),card_back_alt_color:text(x,"card_back_alt_color","#0d9488"),card_front_color:text(x,"card_front_color","#f0fdfa"),card_border_color:text(x,"card_border_color","#115e59"),card_radius:num(x,"card_radius",18,0,40),card_count:Math.round(num(x,"card_count",3,2,6)),card_symbol:text(x,"card_symbol","◆"),reveal_duration:num(x,"reveal_duration",.6,.3,2)}}
export default async function Page({params}:P){const{slug}=await params;if(!slug)notFound();const s=await createSupabaseServerClient();const{data:cg,error}=await s.from("campaign_games").select("id,public_slug,status,appearance,rules,campaigns!inner(id,name,status,starts_at,ends_at),games!inner(id,name,type,description)").eq("public_slug",slug).eq("status","published").maybeSingle();if(error||!cg){if(error)console.error("Load public campaign game error:",error);notFound()}const c=single(cg.campaigns),g=single(cg.games);if(!c||!g)notFound();const now=new Date(),start=c.starts_at?new Date(c.starts_at):null,end=c.ends_at?new Date(c.ends_at):null;if(!(c.status==="active"&&(!start||start<=now)&&(!end||end>=now)))notFound();const{data:prizes,error:pe}=await s.from("prizes").select("id,name,description,image_url,weight,inventory,active,metadata").eq("campaign_game_id",cg.id).eq("active",true).order("created_at",{ascending:true});if(pe){console.error("Load public game prizes error:",pe);notFound()}const d=details(cg.rules as R|null),t=norm(g.type);if(t==="spin"||t==="spin-and-win")return <SpinAndWinGame slug={cg.public_slug} gameName={g.name} prizes={prizes??[]} appearance={spin(cg.appearance as R|null)} customerDetails={d}/>;if(t==="scratch"||t==="scratch-and-win")return <ScratchAndWinGame slug={cg.public_slug} gameName={g.name} appearance={scratch(cg.appearance as R|null)} customerDetails={d}/>;if(t==="pick-a-card"||t==="pick-card"||t==="card")return <PickACardGame slug={cg.public_slug} gameName={g.name} appearance={cards(cg.appearance as R|null)} customerDetails={d}/>;notFound()}
