"use client";
import Link from "next/link";
import { FormEvent, Suspense, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { builderGame, withGame } from "../../lib/game-builder";
import { supabase } from "../../lib/supabase";

function SignupPage(){
 const router=useRouter(); const search=useSearchParams(); const game=builderGame(search.get("game")); const inviteId=search.get("invite")||""; const inviteToken=search.get("token")||""; const inviteHref=inviteId&&inviteToken?`/invite/${encodeURIComponent(inviteId)}?token=${encodeURIComponent(inviteToken)}`:""; const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setError("");setMessage(""); if(password.length<8){setError("Password must be at least 8 characters.");return} if(password!==confirm){setError("Passwords do not match.");return} setLoading(true); const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/auth/callback?next=${encodeURIComponent(inviteHref||withGame("/onboarding",game))}`}}); if(error){setError(error.message);setLoading(false);return} if(data.session){router.push(inviteHref||withGame("/onboarding", game));router.refresh();return} setMessage(inviteHref?"Account created. Confirm your email; the invitation will continue after confirmation.":"Account created. Check your email to confirm your account, then sign in.");setLoading(false)}
 const input={width:"100%",padding:"12px 14px",border:"1px solid #d1d5db",borderRadius:9,marginBottom:16,fontSize:15,boxSizing:"border-box" as const};
 return <main style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",background:"#f6f7f9",padding:20}}><div style={{width:"100%",maxWidth:440,background:"white",border:"1px solid #e5e7eb",borderRadius:16,padding:32}}><p style={{fontSize:11,letterSpacing:".12em",fontWeight:800,color:"#7b8492"}}>MINI-GAME HUB</p><h1>Create your account</h1><p style={{color:"#697386"}}>Start building interactive promotional campaigns for your business.</p>{error&&<p style={{padding:12,background:"#fff0f0",color:"#a11",borderRadius:9}}>{error}</p>}{message&&<p style={{padding:12,background:"#ecfdf5",color:"#065f46",borderRadius:9}}>{message}</p>}<form onSubmit={submit}><label>Email</label><input style={input} type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/><label>Password</label><input style={input} type="password" required autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/><label>Confirm password</label><input style={input} type="password" required autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/><button disabled={loading} style={{width:"100%",padding:13,border:0,borderRadius:9,background:"#111827",color:"white",fontWeight:700}}>{loading?"Creating account...":"Create Account"}</button></form><p style={{textAlign:"center",color:"#697386",fontSize:14}}>Already have an account? <Link href={inviteHref?`/login?invite=${encodeURIComponent(inviteId)}&token=${encodeURIComponent(inviteToken)}`:withGame("/login", game)} style={{fontWeight:700,color:"#111827"}}>Sign in</Link></p></div></main>
}

export default function Page() { return <Suspense fallback={<main style={{padding:40}}>Loading...</main>}><SignupPage /></Suspense>; }
