import { NextResponse } from "next/server";
import { requireAdmin } from "../../../../../../lib/admin-auth";
import { createSupabaseServerClient } from "../../../../../../lib/supabase-server";
type RouteContext={params:Promise<{id:string}>}; const hexColor=/^#[0-9a-fA-F]{6}$/; const alignments=new Set(["left","center","right"]); const fits=new Set(["contain","cover","fill"]); const layers=new Set(["front","normal","back"]); const fontFamilies=new Set(["Arial, sans-serif","Verdana, sans-serif","Tahoma, sans-serif","'Trebuchet MS', sans-serif","Georgia, serif","'Times New Roman', serif","'Courier New', monospace","system-ui, sans-serif"]); const clamp=(v:unknown,min:number,max:number,fallback:number)=>{const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,Math.round(n))):fallback};
export async function PATCH(request:Request,{params}:RouteContext){try{const{workspaceId,role}=await requireAdmin();if(!["owner","admin","editor"].includes(role))return NextResponse.json({error:"You do not have permission to update campaign appearance."},{status:403});const{id}=await params;const body=await request.json();
 const colors=["background_color","card_background_color","button_color","button_text_color","title_color","subtitle_color"] as const;for(const f of colors)if(!hexColor.test(String(body[f]??"")))return NextResponse.json({error:`Invalid color value for ${f}.`},{status:400});
 const titleAlign=String(body.title_align??"center"),subtitleAlign=String(body.subtitle_align??"center"),logoAlign=String(body.logo_align??"center");if(![titleAlign,subtitleAlign,logoAlign].every(v=>alignments.has(v)))return NextResponse.json({error:"Invalid alignment value."},{status:400});
 const titleFontFamily=String(body.title_font_family??"Arial, sans-serif"),subtitleFontFamily=String(body.subtitle_font_family??"Arial, sans-serif");if(!fontFamilies.has(titleFontFamily)||!fontFamilies.has(subtitleFontFamily))return NextResponse.json({error:"Invalid font family."},{status:400});
 const logoFit=String(body.logo_fit??"contain"),logoLayer=String(body.logo_layer??"normal");if(!fits.has(logoFit)||!layers.has(logoLayer))return NextResponse.json({error:"Invalid logo layout setting."},{status:400});const logoUrl=String(body.logo_url??"").trim().slice(0,1000);if(logoUrl){try{const p=new URL(logoUrl);if(!["http:","https:"].includes(p.protocol))throw new Error()}catch{return NextResponse.json({error:"Logo URL must be a valid http or https URL."},{status:400})}}
 const supabase=await createSupabaseServerClient();const{data:subscription,error:subscriptionError}=await supabase.from("workspace_subscriptions").select("status,period_end,subscription_plans(feature_flags)").eq("workspace_id",workspaceId).maybeSingle();if(subscriptionError)return NextResponse.json({error:"Unable to check plan features."},{status:500});const rawPlan=subscription?.subscription_plans;const plan=Array.isArray(rawPlan)?rawPlan[0]:rawPlan;const featureAllowed=subscription?.status==="grandfathered"||(subscription?.status==="active"&&(!subscription.period_end||new Date(subscription.period_end).getTime()>Date.now())&&Boolean((plan?.feature_flags as Record<string,unknown>|undefined)?.custom_branding));if(!featureAllowed)return NextResponse.json({error:"Custom campaign branding is not available on your current plan. Upgrade from Billing to use this feature."},{status:403});const{data:campaign,error:loadError}=await supabase.from("campaigns").select("id, settings").eq("id",id).eq("workspace_id",workspaceId).maybeSingle();if(loadError)return NextResponse.json({error:loadError.message},{status:400});if(!campaign)return NextResponse.json({error:"Campaign not found."},{status:404});const current=campaign.settings&&typeof campaign.settings==="object"&&!Array.isArray(campaign.settings)?campaign.settings as Record<string,unknown>:{};const currentLanding=current.landing&&typeof current.landing==="object"&&!Array.isArray(current.landing)?current.landing as Record<string,unknown>:{};
 const landing={...currentLanding,subtitle:String(body.subtitle??"").trim().slice(0,500),background_color:body.background_color,card_background_color:body.card_background_color,button_color:body.button_color,button_text_color:body.button_text_color,title_bold:Boolean(body.title_bold),title_italic:Boolean(body.title_italic),title_underline:Boolean(body.title_underline),title_align:titleAlign,title_font_size:clamp(body.title_font_size,18,96,54),title_color:body.title_color,title_font_family:titleFontFamily,subtitle_bold:Boolean(body.subtitle_bold),subtitle_italic:Boolean(body.subtitle_italic),subtitle_underline:Boolean(body.subtitle_underline),subtitle_align:subtitleAlign,subtitle_font_size:clamp(body.subtitle_font_size,10,48,17),subtitle_color:body.subtitle_color,subtitle_font_family:subtitleFontFamily,logo_url:logoUrl,logo_align:logoAlign,logo_width:clamp(body.logo_width,40,800,160),logo_height:clamp(body.logo_height,40,800,100),logo_visible:Boolean(body.logo_visible),logo_lock_ratio:Boolean(body.logo_lock_ratio),logo_fit:logoFit,logo_offset_x:clamp(body.logo_offset_x,-500,500,0),logo_offset_y:clamp(body.logo_offset_y,-500,500,0),logo_rotation:clamp(body.logo_rotation,-180,180,0),logo_layer:logoLayer};
 const settings={...current,landing};const{data:updated,error}=await supabase.from("campaigns").update({settings,updated_at:new Date().toISOString()}).eq("id",id).eq("workspace_id",workspaceId).select("id, settings").single();if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({campaign:updated})}catch(error){console.error("Campaign landing settings API error:",error);return NextResponse.json({error:"Unable to update campaign landing settings."},{status:500})}}
