"use client";

import { PointerEvent, useRef, useState } from "react";

type ScratchResult = { session_id?:string; winner_id?:string|null; prize_id?:string; prize_name?:string; prize_description?:string|null; prize_image_url?:string|null; coupon_code?:string|null; replayed?:boolean; is_win?:boolean };
type ScratchAppearance = { title:string; subtitle:string; button_text:string; page_background_color:string; button_color:string; button_text_color:string; scratch_style:string; scratch_cover_color:string; scratch_cover_alt_color:string; scratch_card_background:string; scratch_card_border_color:string; scratch_card_border_thickness:number; scratch_card_radius:number; scratch_instruction:string; scratch_reveal_percent:number };
type Props = { slug:string; gameName:string; appearance:ScratchAppearance };
type RestrictionPopup = { title:string; message:string };

function normalizeMobile(mobile:string){const cleaned=mobile.trim().replace(/\s+/g,"");if(/^07\d{8}$/.test(cleaned))return`+94${cleaned.slice(1)}`;if(/^947\d{8}$/.test(cleaned))return`+${cleaned}`;if(/^\+947\d{8}$/.test(cleaned))return cleaned;return null}

export default function ScratchAndWinGame({slug,gameName,appearance}:Props){
  const [mobile,setMobile]=useState(""); const [loading,setLoading]=useState(false); const [result,setResult]=useState<ScratchResult|null>(null); const [error,setError]=useState(""); const [restrictionPopup,setRestrictionPopup]=useState<RestrictionPopup|null>(null); const [scratched,setScratched]=useState<Set<number>>(new Set()); const [revealed,setRevealed]=useState(false); const dragging=useRef(false);
  async function startGame(){setError("");setRestrictionPopup(null);setResult(null);setScratched(new Set());setRevealed(false);if(!normalizeMobile(mobile)){setError("Please enter a valid Sri Lankan mobile number.");return}setLoading(true);try{const response=await fetch(`/api/play/${slug}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mobile})});const data=await response.json();if(!response.ok){if(data.error_title)setRestrictionPopup({title:data.error_title,message:data.error||"Unable to play the game."});else setError(data.error||"Unable to play the game.");return}setResult(data.result as ScratchResult)}catch{setError("Unable to connect to the game. Please try again.")}finally{setLoading(false)}}
  function scratchAt(event:PointerEvent<HTMLDivElement>){if(!result||revealed)return;const rect=event.currentTarget.getBoundingClientRect();const x=Math.max(0,Math.min(rect.width-1,event.clientX-rect.left));const y=Math.max(0,Math.min(rect.height-1,event.clientY-rect.top));const cols=10,rows=6,col=Math.floor(x/rect.width*cols),row=Math.floor(y/rect.height*rows);const next=new Set(scratched);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const c=col+dx,r=row+dy;if(c>=0&&c<cols&&r>=0&&r<rows)next.add(r*cols+c)}setScratched(next);const needed=Math.max(1,Math.ceil(60*appearance.scratch_reveal_percent/100));if(next.size>=needed)setRevealed(true)}
  const isWin=result?.is_win!==false; const progress=Math.min(100,Math.round(scratched.size/60*100));
  const inputStyle={width:"100%",boxSizing:"border-box" as const,border:"1px solid #d1d5db",borderRadius:12,padding:"13px 14px",fontSize:16};
  return <main style={{minHeight:"100vh",background:appearance.page_background_color,padding:"32px 16px 48px"}}><div style={{width:"100%",maxWidth:680,margin:"0 auto"}}><section style={{background:"#fff",borderRadius:24,padding:"34px 22px 38px",boxShadow:"0 12px 40px rgba(0,0,0,.10)",textAlign:"center"}}>
    <div style={{fontSize:34,fontWeight:900,color:"#111827",marginBottom:8}}>{appearance.title}</div><div style={{color:"#6b7280",fontSize:16,marginBottom:6}}>{appearance.subtitle}</div><div style={{color:"#374151",fontWeight:700,fontSize:14,marginBottom:26}}>{gameName}</div>
    {!result?<div style={{maxWidth:420,margin:"0 auto"}}><label htmlFor="scratch-mobile" style={{display:"block",textAlign:"left",fontSize:14,fontWeight:700,marginBottom:7}}>Mobile Number</label><input id="scratch-mobile" type="tel" placeholder="07XXXXXXXX" value={mobile} onChange={e=>setMobile(e.target.value)} disabled={loading} style={inputStyle}/>{error&&<div style={{color:"#b91c1c",background:"#fef2f2",padding:11,borderRadius:10,marginTop:12,textAlign:"left"}}>{error}</div>}<button type="button" onClick={startGame} disabled={loading||!mobile.trim()} style={{width:"100%",marginTop:14,border:"none",borderRadius:12,padding:15,fontSize:17,fontWeight:900,background:appearance.button_color,color:appearance.button_text_color,cursor:"pointer",opacity:loading||!mobile.trim()?.55:1}}>{loading?"PREPARING...":appearance.button_text}</button></div>:<>
      <div onPointerDown={e=>{dragging.current=true;e.currentTarget.setPointerCapture(e.pointerId);scratchAt(e)}} onPointerMove={e=>{if(dragging.current)scratchAt(e)}} onPointerUp={()=>{dragging.current=false}} onPointerCancel={()=>{dragging.current=false}} style={{position:"relative",width:"min(88vw,480px)",height:280,margin:"0 auto",borderRadius:appearance.scratch_card_radius,overflow:"hidden",border:`${appearance.scratch_card_border_thickness}px solid ${appearance.scratch_card_border_color}`,userSelect:"none",touchAction:"none",background:appearance.scratch_card_background,cursor:revealed?"default":"crosshair"}}>
        <div style={{position:"absolute",inset:0,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:24,background:isWin?appearance.scratch_card_background:"#f9fafb"}}><div style={{fontSize:42,marginBottom:8}}>{isWin?"🎉":"↻"}</div><div style={{fontSize:13,fontWeight:900,color:"#6b7280",letterSpacing:".08em",marginBottom:7}}>{isWin?"CONGRATULATIONS!":"TRY AGAIN"}</div><div style={{fontSize:30,fontWeight:900,color:"#111827"}}>{result.prize_name||(isWin?"YOU WON!":"Better luck next time")}</div>{result.prize_description&&<div style={{color:"#6b7280",marginTop:8}}>{result.prize_description}</div>}</div>
        {!revealed&&Array.from({length:60},(_,i)=>!scratched.has(i)&&<div key={i} style={{position:"absolute",left:`${i%10*10}%`,top:`${Math.floor(i/10)*(100/6)}%`,width:"10.5%",height:`${100/6+.5}%`,background:i%2?appearance.scratch_cover_alt_color:appearance.scratch_cover_color,border:"1px solid rgba(255,255,255,.12)",boxSizing:"border-box",pointerEvents:"none"}}/>)}
        {!revealed&&scratched.size<5&&<div style={{position:"absolute",inset:0,display:"flex",alignItems:"center",justifyContent:"center",pointerEvents:"none",color:"#fff",fontWeight:900,fontSize:22,textShadow:"0 2px 4px rgba(0,0,0,.4)"}}>{appearance.scratch_instruction}</div>}
      </div><div style={{marginTop:14,color:"#6b7280",fontSize:14}}>{revealed?"Your result has been revealed.":`Scratch the area to reveal your result (${progress}%)`}</div>{revealed&&result.replayed&&<div style={{marginTop:10,fontWeight:700,color:"#6b7280"}}>This is your previous result.</div>}{revealed&&isWin&&result.coupon_code&&<div style={{margin:"18px auto 0",maxWidth:360,padding:15,borderRadius:14,background:"#f0fdf4",border:"1px solid #bbf7d0"}}><div style={{fontSize:12,fontWeight:800,color:"#166534"}}>COUPON CODE</div><div style={{fontSize:24,fontWeight:900,letterSpacing:".06em",marginTop:4}}>{result.coupon_code}</div></div>}</>}
  </section></div>{restrictionPopup&&<div style={{position:"fixed",inset:0,zIndex:10000,background:"rgba(17,24,39,.72)",display:"flex",alignItems:"center",justifyContent:"center",padding:20}}><div style={{position:"relative",width:"100%",maxWidth:420,background:"#fff",borderRadius:24,padding:"36px 24px 28px",textAlign:"center"}}><button onClick={()=>setRestrictionPopup(null)} style={{position:"absolute",top:14,right:14,border:"none",background:"transparent",fontSize:22,cursor:"pointer"}}>×</button><div style={{fontSize:24,fontWeight:900,marginBottom:12}}>{restrictionPopup.title}</div><div style={{color:"#6b7280",marginBottom:22,lineHeight:1.5}}>{restrictionPopup.message}</div><button onClick={()=>setRestrictionPopup(null)} style={{width:"100%",border:"none",borderRadius:12,padding:13,background:appearance.button_color,color:appearance.button_text_color,fontWeight:800}}>OK</button></div></div>}</main>
}
