"use client";

import { useEffect, useState } from "react";
import type { CSSProperties, ChangeEvent } from "react";
import { DEFAULT_HOMEPAGE_CONTENT, GAME_CATALOG, type HomepageContent, type HomepageGameCard, type HomepageTypography, type SeasonalTheme } from "../../../lib/homepage-content";

type Metadata = { updatedAt: string | null; publishedAt: string | null; canEdit: boolean };
const ICONS = ["↻", "✦", "◆", "★", "🎁", "🎯", "🎲", "🏆", "🎮", "🃏", "🎉", "💎", "🎈", "⚡", "🌟", "🎊", "🍀", "🎵", "🚀", "❤️"];
const FONTS = ["Arial, sans-serif", "Georgia, serif", "Verdana, sans-serif", "Trebuchet MS, sans-serif", "Tahoma, sans-serif", "system-ui, sans-serif"];
const THEME_COLORS: Record<SeasonalTheme["preset"], Pick<SeasonalTheme, "primary" | "accent" | "heroBackground" | "pageBackground">> = {
  christmas: { primary: "#b4232c", accent: "#35a36b", heroBackground: "#163529", pageBackground: "#f4f8f4" },
  "new-year": { primary: "#a77812", accent: "#f2cc63", heroBackground: "#182039", pageBackground: "#f7f6f1" },
  ramadan: { primary: "#14816f", accent: "#d9b45a", heroBackground: "#123b3a", pageBackground: "#f3f8f5" },
  custom: { primary: "#e31b23", accent: "#ff5b61", heroBackground: "#101828", pageBackground: "#f6f7f9" },
};
function TextField({ label, value, onChange, multiline = false }: { label: string; value: string; onChange: (value: string) => void; multiline?: boolean }) {
  return <label className="home-field"><span>{label}</span>{multiline ? <textarea value={value} onChange={(e) => onChange(e.target.value)} rows={3} /> : <input value={value} onChange={(e) => onChange(e.target.value)} />}</label>;
}
function ColorField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) {
  return <label className="home-color-field"><span>{label}</span><input type="color" value={value} onChange={(e) => onChange(e.target.value)} /><code>{value}</code></label>;
}
function TypographyEditor({ value, onChange }: { value: HomepageTypography; onChange: (next: HomepageTypography) => void }) {
  const set = (key: keyof HomepageTypography, next: string | number | boolean) => onChange({ ...value, [key]: next } as HomepageTypography);
  return <div className="home-type-controls">
    <label className="home-field"><span>Font family</span><select value={value.fontFamily} onChange={(e) => set("fontFamily", e.target.value)}>{FONTS.map((font) => <option key={font} value={font}>{font.split(",")[0]}</option>)}</select></label>
    <label className="home-field"><span>Font size: {value.fontSize}px</span><input type="range" min="10" max="48" value={value.fontSize} onChange={(e) => set("fontSize", Number(e.target.value))} /></label>
    <label className="home-field"><span>Headline size</span><select value={value.headlineSize} onChange={(e) => set("headlineSize", Number(e.target.value))}>{[24, 28, 32, 36, 42, 48, 56, 64, 72].map((size) => <option key={size} value={size}>{size}px</option>)}</select></label>
    <label className="home-field"><span>Text alignment</span><select value={value.alignment} onChange={(e) => set("alignment", e.target.value)}><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></label>
    <div className="home-format-options"><label><input type="checkbox" checked={value.bold} onChange={(e) => set("bold", e.target.checked)} /><b>B</b> Bold</label><label><input type="checkbox" checked={value.italic} onChange={(e) => set("italic", e.target.checked)} /><i>I</i> Italic</label><label><input type="checkbox" checked={value.underline} onChange={(e) => set("underline", e.target.checked)} /><u>U</u> Underline</label></div>
  </div>;
}
function FileUpload({ label, value, onUpload, busy }: { label: string; value: string; onUpload: (file: File) => void; busy: boolean }) {
  return <label className="home-upload"><span>{label}</span><input type="file" accept="image/png,image/jpeg,image/webp,image/avif" disabled={busy} onChange={(e: ChangeEvent<HTMLInputElement>) => { const file = e.target.files?.[0]; if (file) onUpload(file); e.target.value = ""; }} />{value && <img src={value} alt="Uploaded preview" />}{busy && <small>Uploading…</small>}</label>;
}
export default function HomepageManager() {
  const [content, setContent] = useState<HomepageContent>(DEFAULT_HOMEPAGE_CONTENT);
  const [published, setPublished] = useState<HomepageContent>(DEFAULT_HOMEPAGE_CONTENT);
  const [metadata, setMetadata] = useState<Metadata>({ updatedAt: null, publishedAt: null, canEdit: false });
  const [status, setStatus] = useState("Loading homepage settings…");
  const [busy, setBusy] = useState(false);
  const [uploading, setUploading] = useState("");
  const [newPreset, setNewPreset] = useState<SeasonalTheme["preset"]>("christmas");
  useEffect(() => { fetch("/api/saas-admin/homepage").then(async (r) => { const result = await r.json(); if (!r.ok) throw new Error(result.error || "Unable to load homepage settings."); setContent(result.draft); setPublished(result.published); setMetadata({ updatedAt: result.updatedAt, publishedAt: result.publishedAt, canEdit: result.canEdit }); setStatus(""); }).catch((e) => setStatus(e instanceof Error ? e.message : "Unable to load settings.")); }, []);

  const updateGroup = (group: "header" | "hero" | "games" | "how" | "footer" | "theme", field: string, value: string | boolean | number) => setContent((c) => ({ ...c, [group]: { ...c[group], [field]: value } }));
  const updateType = (section: keyof HomepageContent["typography"], value: HomepageTypography) => setContent((c) => ({ ...c, typography: { ...c.typography, [section]: value } }));
  const updateCard = (id: HomepageGameCard["id"], field: keyof HomepageGameCard, value: string | number) => setContent((c) => ({ ...c, games: { ...c.games, cards: c.games.cards.map((card) => card.id === id ? { ...card, [field]: value } : card) } }));
  const updateStep = (index: number, field: "title" | "description", value: string) => setContent((c) => ({ ...c, how: { ...c.how, steps: c.how.steps.map((step, i) => i === index ? { ...step, [field]: value } : step) } }));
  const updateTheme = (id: string, field: keyof SeasonalTheme, value: string | boolean) => setContent((c) => ({ ...c, seasonalThemes: c.seasonalThemes.map((theme) => theme.id === id ? { ...theme, [field]: value } : theme) }));
  async function upload(file: File, destination: "logo" | HomepageGameCard["id"]) {
    if (file.size > 3 * 1024 * 1024) { setStatus("Choose an image smaller than 3 MB."); return; }
    setUploading(destination); setStatus("");
    try { const form = new FormData(); form.set("file", file); const response = await fetch("/api/saas-admin/homepage/assets", { method: "POST", body: form }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Image upload failed."); if (destination === "logo") updateGroup("header", "logoUrl", result.url); else updateCard(destination, "imageUrl", result.url); setStatus("Image uploaded. Save or publish to apply it."); }
    catch (e) { setStatus(e instanceof Error ? e.message : "Image upload failed."); } finally { setUploading(""); }
  }
  async function save(action: "save" | "publish") {
    setBusy(true); setStatus("");
    try { const response = await fetch("/api/saas-admin/homepage", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, content }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Unable to save settings."); setMetadata((m) => ({ ...m, updatedAt: result.updatedAt, publishedAt: result.publishedAt ?? m.publishedAt })); if (action === "publish") setPublished(content); setStatus(action === "publish" ? "Homepage published. Scheduled seasonal themes will activate on their selected dates." : "Draft saved."); }
    catch (e) { setStatus(e instanceof Error ? e.message : "Unable to save settings."); } finally { setBusy(false); }
  }
  function addTheme() { const name = { christmas: "Christmas", "new-year": "New Year", ramadan: "Ramadan", custom: "Seasonal theme" }[newPreset]; setContent((c) => ({ ...c, seasonalThemes: [...c.seasonalThemes, { id: crypto.randomUUID(), name, preset: newPreset, startsAt: "", endsAt: "", announcement: "", enabled: true, ...THEME_COLORS[newPreset] }] })); }
  function addCard(id: HomepageGameCard["id"]) { const base = DEFAULT_HOMEPAGE_CONTENT.games.cards.find((c) => c.id === id); if (base) setContent((c) => ({ ...c, games: { ...c.games, cards: [...c.games.cards, { ...base }] } })); }
  const previewStyle = { "--home-primary": content.theme.primary, "--home-accent": content.theme.accent, "--home-hero": content.theme.heroBackground, "--home-bg": content.theme.pageBackground } as CSSProperties;
  const typeStyle = (section: keyof HomepageContent["typography"], headline = false): CSSProperties => { const t = content.typography[section]; return { fontFamily: t.fontFamily, fontSize: headline ? `${t.headlineSize}px` : `${t.fontSize}px`, fontWeight: t.bold ? 800 : undefined, fontStyle: t.italic ? "italic" : undefined, textDecoration: t.underline ? "underline" : undefined, textAlign: t.alignment }; };
  return <>
    <div className="admin-header"><div><div className="eyebrow">PUBLIC WEBSITE</div><h1>Homepage layout</h1><p>Customize the homepage, game cards and seasonal themes.</p></div><div className="home-actions"><button className="home-secondary" onClick={() => setContent(published)} disabled={!metadata.canEdit || busy}>Discard draft</button><button className="primary-btn" onClick={() => save("save")} disabled={busy || !metadata.canEdit}>Save draft</button><button className="primary-btn home-publish" onClick={() => save("publish")} disabled={busy || !metadata.canEdit}>Publish</button></div></div>
    {status && <div className={status.includes("Unable") || status.includes("Choose") || status.includes("failed") ? "error-box" : "home-notice"}>{status}</div>}
    {!metadata.canEdit && !status && <div className="home-notice">View only access. Ask a Super Admin or Admin to edit and publish homepage content.</div>}
    <div className="homepage-editor-grid"><fieldset className="homepage-edit-column home-editor-fieldset" disabled={!metadata.canEdit || busy}>
      <section className="admin-panel home-editor-panel"><div className="home-panel-heading"><div><span className="home-step-index">01</span><h2>Header</h2></div><small>Logo, announcement and navigation</small></div>
        <div className="home-fields"><TextField label="Brand name" value={content.header.brand} onChange={(v) => updateGroup("header", "brand", v)} /><FileUpload label="Upload logo" value={content.header.logoUrl} busy={uploading === "logo"} onUpload={(f) => upload(f, "logo")} /><TextField label="Announcement text" value={content.header.announcement} onChange={(v) => updateGroup("header", "announcement", v)} /></div>
        <div className="home-format-options"><label><input type="checkbox" checked={content.header.showLogo} onChange={(e) => updateGroup("header", "showLogo", e.target.checked)} /> Show logo</label><label><input type="checkbox" checked={content.header.showBrand} onChange={(e) => updateGroup("header", "showBrand", e.target.checked)} /> Show brand name</label></div>
        <label className="home-check"><input type="checkbox" checked={content.header.showAnnouncement} onChange={(e) => updateGroup("header", "showAnnouncement", e.target.checked)} /> Show announcement bar</label>
        <h3 className="home-subheading">Navigation labels and visibility</h3><div className="home-nav-fields">{([ ["Home", "navHome", "showHome"], ["Games", "navGames", "showGames"], ["How it works", "navHow", "showHow"], ["Sign in", "navSignIn", "showSignIn"], ["Get started", "navGetStarted", "showGetStarted"] ] as const).map(([label, textKey, showKey]) => <div className="home-nav-row" key={textKey}><TextField label={label + " label"} value={content.header[textKey]} onChange={(v) => updateGroup("header", textKey, v)} /><label className="home-check"><input type="checkbox" checked={content.header[showKey]} onChange={(e) => updateGroup("header", showKey, e.target.checked)} /> Show</label></div>)}</div>
        <h3 className="home-subheading">Header typography</h3><TypographyEditor value={content.typography.header} onChange={(v) => updateType("header", v)} />
      </section>
      <section className="admin-panel home-editor-panel"><div className="home-panel-heading"><div><span className="home-step-index">02</span><h2>Body sections</h2></div><small>Hero, games and how it works</small></div>
        <div className="home-section-toggles"><label className="home-check"><input type="checkbox" checked={content.sections.showHero} onChange={(e) => setContent((c) => ({ ...c, sections: { ...c.sections, showHero: e.target.checked } }))} /> Show hero</label><label className="home-check"><input type="checkbox" checked={content.sections.showGames} onChange={(e) => setContent((c) => ({ ...c, sections: { ...c.sections, showGames: e.target.checked } }))} /> Show games</label><label className="home-check"><input type="checkbox" checked={content.sections.showHow} onChange={(e) => setContent((c) => ({ ...c, sections: { ...c.sections, showHow: e.target.checked } }))} /> Show how it works</label><label className="home-check"><input type="checkbox" checked={content.sections.showFooter} onChange={(e) => setContent((c) => ({ ...c, sections: { ...c.sections, showFooter: e.target.checked } }))} /> Show footer</label></div><h3 className="home-subheading">Hero section</h3><div className="home-fields"><TextField label="Eyebrow" value={content.hero.eyebrow} onChange={(v) => updateGroup("hero", "eyebrow", v)} /><TextField label="Main heading" value={content.hero.title} onChange={(v) => updateGroup("hero", "title", v)} /><TextField label="Highlighted heading" value={content.hero.highlight} onChange={(v) => updateGroup("hero", "highlight", v)} /><TextField label="Primary button" value={content.hero.primaryCta} onChange={(v) => updateGroup("hero", "primaryCta", v)} /><TextField label="Secondary button" value={content.hero.secondaryCta} onChange={(v) => updateGroup("hero", "secondaryCta", v)} /><TextField label="Description" value={content.hero.description} onChange={(v) => updateGroup("hero", "description", v)} multiline /></div><h3 className="home-subheading">Hero typography</h3><TypographyEditor value={content.typography.hero} onChange={(v) => updateType("hero", v)} />
        <h3 className="home-subheading">Games section</h3><div className="home-fields"><TextField label="Eyebrow" value={content.games.eyebrow} onChange={(v) => updateGroup("games", "eyebrow", v)} /><TextField label="Section title" value={content.games.title} onChange={(v) => updateGroup("games", "title", v)} /><TextField label="Section note" value={content.games.description} onChange={(v) => updateGroup("games", "description", v)} /><label className="home-field"><span>Cards per row / columns</span><select value={content.games.columns} onChange={(e) => updateGroup("games", "columns", Number(e.target.value))}>{[1, 2, 3, 4].map((n) => <option key={n} value={n}>{n} column{n > 1 ? "s" : ""}</option>)}</select></label></div><h3 className="home-subheading">Games section typography</h3><TypographyEditor value={content.typography.games} onChange={(v) => updateType("games", v)} />
        <div className="home-card-list">{content.games.cards.map((card) => <article className="home-game-editor" key={card.id}><div className="home-game-editor-heading"><b>{GAME_CATALOG.find((game) => game.id === card.id)?.label}</b><button type="button" className="home-remove" onClick={() => setContent((c) => ({ ...c, games: { ...c.games, cards: c.games.cards.filter((item) => item.id !== card.id) } }))}>Remove card</button></div>
          <div className="home-fields"><TextField label="Card title" value={card.title} onChange={(v) => updateCard(card.id, "title", v)} /><TextField label="Button label" value={card.action} onChange={(v) => updateCard(card.id, "action", v)} /><TextField label="Description" value={card.description} onChange={(v) => updateCard(card.id, "description", v)} multiline /><label className="home-field"><span>Card icon</span><select value={card.icon} onChange={(e) => updateCard(card.id, "icon", e.target.value)}>{ICONS.map((icon) => <option key={icon} value={icon}>{icon}</option>)}</select></label><label className="home-field"><span>Text alignment</span><select value={card.textAlignment} onChange={(e) => updateCard(card.id, "textAlignment", e.target.value)}><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></label><label className="home-field"><span>Card height: {card.height}px</span><input type="range" min="140" max="600" value={card.height} onChange={(e) => updateCard(card.id, "height", Number(e.target.value))} /></label><label className="home-field"><span>Card width: {card.width}%</span><input type="range" min="50" max="100" value={card.width} onChange={(e) => updateCard(card.id, "width", Number(e.target.value))} /></label><label className="home-field"><span>Corner radius: {card.cornerRadius}px</span><input type="range" min="0" max="48" value={card.cornerRadius} onChange={(e) => updateCard(card.id, "cornerRadius", Number(e.target.value))} /></label></div>
          <div className="home-colors compact"><ColorField label="Card color" value={card.color} onChange={(v) => updateCard(card.id, "color", v)} /><ColorField label="Text color" value={card.textColor} onChange={(v) => updateCard(card.id, "textColor", v)} /></div><FileUpload label="Upload card image" value={card.imageUrl} busy={uploading === card.id} onUpload={(f) => upload(f, card.id)} /></article>)}</div>
        <div className="home-add-card"><label className="home-field"><span>Add a game card</span><select id="home-add-game" defaultValue=""> <option value="" disabled>Select a game</option>{GAME_CATALOG.filter((g) => !content.games.cards.some((c) => c.id === g.id)).map((g) => <option key={g.id} value={g.id}>{g.label}</option>)}</select></label><button type="button" className="home-secondary" disabled={content.games.cards.length >= GAME_CATALOG.length || !GAME_CATALOG.some((g) => !content.games.cards.some((c) => c.id === g.id))} onClick={() => { const select = document.getElementById("home-add-game") as HTMLSelectElement | null; if (select?.value) { addCard(select.value as HomepageGameCard["id"]); select.value = ""; } }}>Add card</button></div>
        <h3 className="home-subheading">How it works</h3><div className="home-fields"><TextField label="Eyebrow" value={content.how.eyebrow} onChange={(v) => updateGroup("how", "eyebrow", v)} /><TextField label="Section title" value={content.how.title} onChange={(v) => updateGroup("how", "title", v)} />{content.how.steps.map((step, i) => <div className="home-step-fields" key={i}><b>Step {i + 1}</b><TextField label="Title" value={step.title} onChange={(v) => updateStep(i, "title", v)} /><TextField label="Description" value={step.description} onChange={(v) => updateStep(i, "description", v)} multiline /></div>)}</div><h3 className="home-subheading">How it works typography</h3><TypographyEditor value={content.typography.how} onChange={(v) => updateType("how", v)} />
      </section>
      <section className="admin-panel home-editor-panel"><div className="home-panel-heading"><div><span className="home-step-index">03</span><h2>Footer</h2></div><small>Copyright and link labels</small></div><div className="home-fields"><TextField label="Copyright" value={content.footer.copyright} onChange={(v) => updateGroup("footer", "copyright", v)} /><TextField label="Terms link label" value={content.footer.termsLabel} onChange={(v) => updateGroup("footer", "termsLabel", v)} /><TextField label="Privacy link label" value={content.footer.privacyLabel} onChange={(v) => updateGroup("footer", "privacyLabel", v)} /></div><h3 className="home-subheading">Footer typography</h3><TypographyEditor value={content.typography.footer} onChange={(v) => updateType("footer", v)} /></section>
      <section className="admin-panel home-editor-panel"><div className="home-panel-heading"><div><span className="home-step-index">04</span><h2>Brand theme</h2></div><small>Default homepage colors</small></div><div className="home-colors">{(["primary", "accent", "heroBackground", "pageBackground"] as const).map((key) => <ColorField key={key} label={{ primary: "Primary", accent: "Accent", heroBackground: "Hero background", pageBackground: "Page background" }[key]} value={content.theme[key]} onChange={(v) => updateGroup("theme", key, v)} />)}</div></section>
      <section className="admin-panel home-editor-panel"><div className="home-panel-heading"><div><span className="home-step-index">05</span><h2>Seasonal themes</h2></div><small>Set a theme and schedule its dates</small></div><div className="seasonal-add-row"><select value={newPreset} onChange={(e) => setNewPreset(e.target.value as SeasonalTheme["preset"])}><option value="christmas">Christmas</option><option value="new-year">New Year</option><option value="ramadan">Ramadan</option><option value="custom">Custom palette</option></select><button type="button" className="home-secondary" onClick={addTheme} disabled={content.seasonalThemes.length >= 12}>Add seasonal theme</button></div>{content.seasonalThemes.map((theme) => <article className="seasonal-theme-card" key={theme.id}><div className="seasonal-theme-top"><strong>{theme.name}</strong><label className="home-check"><input type="checkbox" checked={theme.enabled} onChange={(e) => updateTheme(theme.id, "enabled", e.target.checked)} /> Enabled</label><button type="button" className="home-remove" onClick={() => setContent((c) => ({ ...c, seasonalThemes: c.seasonalThemes.filter((t) => t.id !== theme.id) }))}>Remove</button></div><div className="home-fields"><TextField label="Theme name" value={theme.name} onChange={(v) => updateTheme(theme.id, "name", v)} /><TextField label="Announcement" value={theme.announcement} onChange={(v) => updateTheme(theme.id, "announcement", v)} /></div><div className="seasonal-date-row"><label className="home-field"><span>Starts</span><input type="date" value={theme.startsAt} onChange={(e) => updateTheme(theme.id, "startsAt", e.target.value)} /></label><label className="home-field"><span>Ends</span><input type="date" value={theme.endsAt} onChange={(e) => updateTheme(theme.id, "endsAt", e.target.value)} /></label></div><div className="home-colors compact">{(["primary", "accent", "heroBackground", "pageBackground"] as const).map((key) => <ColorField key={key} label={{ primary: "Primary", accent: "Accent", heroBackground: "Hero", pageBackground: "Page" }[key]} value={theme[key]} onChange={(v) => updateTheme(theme.id, key, v)} />)}</div></article>)}</section>
    </fieldset>
    <aside className="homepage-preview-wrap"><div className="homepage-preview-title"><div><div className="eyebrow">LIVE PREVIEW</div><h2>Homepage</h2></div><span>Draft</span></div><div className="homepage-preview" style={previewStyle}><header className="preview-header" style={typeStyle("header")}>{content.header.showLogo && (content.header.logoUrl ? <img src={content.header.logoUrl} alt="Logo" /> : <span className="brandmark">M</span>)}{content.header.showBrand && <b>{content.header.brand}</b>}<nav>{content.header.showHome && <span>{content.header.navHome}</span>}{content.header.showGames && <span>{content.header.navGames}</span>}{content.header.showHow && <span>{content.header.navHow}</span>}{content.header.showSignIn && <span>{content.header.navSignIn}</span>}{content.header.showGetStarted && <span>{content.header.navGetStarted}</span>}</nav></header>{content.header.showAnnouncement && <div className="preview-announcement">{content.header.announcement}</div>}{content.sections.showHero && <section className="preview-hero" style={typeStyle("hero")}><small>{content.hero.eyebrow}</small><h3 style={typeStyle("hero", true)}>{content.hero.title} {content.hero.highlight}</h3><p>{content.hero.description}</p><button>{content.hero.primaryCta}</button></section>}{content.sections.showGames && <section className="preview-body" style={typeStyle("games")}><small>{content.games.eyebrow}</small><h3 style={typeStyle("games", true)}>{content.games.title}</h3><div className="preview-game-cards" style={{ gridTemplateColumns: `repeat(${content.games.columns},minmax(0,1fr))` }}>{content.games.cards.map((card) => <article key={card.id} style={{ background: card.color, color: card.textColor, borderRadius: card.cornerRadius, height: Math.min(150, Math.max(85, card.height / 2)), width: `${card.width}%`, marginInline: "auto", textAlign: card.textAlignment }}><div className="preview-card-art" style={{ background: card.imageUrl ? `url("${card.imageUrl}") center/cover` : "transparent" }}>{!card.imageUrl && card.icon}</div><b>{card.title}</b><span>{card.description}</span></article>)}</div></section>}{content.sections.showHow && <section className="preview-body" style={typeStyle("how")}><small>{content.how.eyebrow}</small><h3 style={typeStyle("how", true)}>{content.how.title}</h3></section>}{content.sections.showFooter && <footer style={typeStyle("footer")}>{content.footer.copyright}<br />{content.footer.termsLabel}　{content.footer.privacyLabel}</footer>}</div><div className="homepage-version-note">{metadata.publishedAt ? `Last published ${new Date(metadata.publishedAt).toLocaleString()}` : "Not published yet"}</div></aside></div>
  </>;
}
